##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. ee MIT LICENSE
## file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_indexes
description: A starting point for Dart or Flutter packages.
version: 0.1.0
repository: https://github.com/robmllze/df_generate_dart_indexes

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  args: ^2.5.0
  df_config: ^0.1.0
  df_gen_core: ^0.1.0
  df_log: ^0.1.0
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

## -----------------------------------------------------------------------------

executables:
  generate_dart_indexes: bin/generate_dart_indexes.dart
