##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_dart_indexes
description: A tool to generate index/exports files also known as barrel files for all Dart files in a directory.
version: 0.2.1
repository: https://github.com/robmllze/df_generate_dart_indexes
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - barrel-file
  - build-runner
  - cli
  - codegen
  - index

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  args: ^2.5.0
  df_config: ^0.3.0
  df_gen_core: ^0.2.7
  df_log: ^0.2.1
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  genidx: genidx-dart
  genidx-dart: genidx-dart
